spring:
  application:
    name: prom-v2-eureka-service
    heroku: ${spring.application.name}.herokuapp.com
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: ${PORT:2011} #Heroku will supply it's own value here

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost} #EUREKA_HOSTNAME var set to => prom-v2-eureka-service.herokuapp.com on herkou dashboard
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    service-url:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka
      non-secure-port: ${PORT:2011}
      secure-port: 443

feign:
  client:
    config:
      default:
        connectTimeout: 10000 #milliseconds
        readTimeout: 10000